<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE folks [
    <!ELEMENT folks (person+)>
    <!ELEMENT person (name)>
    <!ATTLIST person pin ID #REQUIRED>
    <!ATTLIST person friend IDREF #IMPLIED>
    <!ATTLIST person likes IDREFS #IMPLIED>
    <!ELEMENT name (#PCDATA)>
]>

<folks>
    <person pin="p1">
        <name>Paula</name>
    </person>
    <person pin="p2" friend="p1">
        <name>Gonzalo</name>
    </person>
    <person pin="p3" likes="p2 p1">
        <name>Catuxa</name>
    </person>
</folks>
