=== michaelBedDev/validating_XML/items/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="photo" type="xs:string"/>
                            <xs:element name="tags" type="xs:string"/>
                            <xs:element name="diameter">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="unit" type="xs:string"></xs:attribute>
                                        </xs:extension>
                                </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="weight" type="xs:positiveInteger"/>
                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:fractionDigits value="2"></xs:fractionDigits>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="size" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Big|Small|"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== michaelBedDev/validating_XML/items/items.xml
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="items.xsd">
    <item>
        <name>Jarron</name>
        <photo>jarron.png</photo>
        <tags>deco</tags>
        <diameter unit="cm">45</diameter>
        <weight>2</weight>
        <price>55.21</price>
        <size>Big</size>
    </item>
</items>
